name: Hanlde issues
on:
  issues:
    types: [opened, edited, milestoned]
jobs:
  output-info:
    runs-on: ubuntu-latest
    steps:
      - name: Output event Details
        run: echo "${{ toJSON(github.event) }}"
